version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '09:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 10
    groups:
      fontawesome:
        patterns:
          - '@fortawesome/*'
      shlink:
        patterns:
          - '@shlinkio/*'
      types:
        patterns:
          - '@types/*'
      testing:
        patterns:
          - '@testing-library/*'
      vite:
        patterns:
          - 'vite'
          - 'vite-plugin-dts'
          - '@vitejs/*'
      vitest:
        patterns:
          - 'vitest'
          - 'vitest-canvas-mock'
          - '@vitest/*'
    ignore:
      # Bootstrap can introduce visual breaking changes on styles
      # Ignore it, since the plan is to remove it anyway
      - dependency-name: 'bootstrap'
