services:
    shlink_frontend_kit:
        container_name: shlink_frontend_kit
        user: 1000:1000
        build:
            context: .
        working_dir: /shlink-frontend-kit
        command: /bin/sh -c "npm i && node --run dev"
        volumes:
            - ./:/shlink-frontend-kit
        ports:
            - '3001:3001'
